name: ${project.name}
version:  ${project.version}
author: Alkarin

description: Capture the flag event using Arenas
depend: [BattleArena-lite]
main: mc.alk.ctf.CTF
commands:
    ctf:
        aliases: [captureTheFlag]
permissions:
    ctf.*:
        default: op
    battlearena.ctf.*:
        default: op
    arena.join.ctf:
        default: true
        
